### PR TITLE
Add json-download option for timeline data

### PR DESCRIPTION
**Pull request by jeremyh**
strangely the test file was not fully black-formatted. I wonder if pre-commit has started skipping the tests folder?

### CODE REVIEW

**Comment by jeremyh** [comment]
Addresses  #465

**Comment by jeremyh** [comment]
@pindge the new docs-QA action seems to be failing repeatedly?

**Comment by pindge** [comment]
> @pindge the new docs-QA action seems to be failing repeatedly?

the build succeed, the issue is it doesn't have permission to edit the pr's comment, 

```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6172:21
Error: Unhandled error: HttpError: Resource not accessible by integration
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/opendatacube/datacube-explorer/pulls/467',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 07 Nov 2022 22:35:10 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=3[153](https://github.com/opendatacube/datacube-explorer/actions/runs/3408246965/jobs/5682854972#step:2:163)6000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3',
      'x-github-request-id': '0484:98D8:B8200:BD743:6369881E',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '994',
      'x-ratelimit-reset': '1667860940',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '6',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/reference/pulls#update-a-pull-request'
    }
  },
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/opendatacube/datacube-explorer/pulls/467',
    headers: {
      accept: 'application/vnd.github.-preview+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.13.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"strangely the test file was not fully black-formatted. I wonder if pre-commit has started skipping the tests folder?\\r\\n\\r\\n<!-- readthedocs-preview datacube-explorer start -->\\r\\n----\\n:books: Documentation preview :books:: https://datacube-explorer--467.org.readthedocs.build/en/467/\\n\\r\\n<!-- readthedocs-preview datacube-explorer end -->"}',
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
```

**Comment by omad** [comment]
@jeremyh Thanks, this looks great.

We need to keep in better touch, I'd had this in mind as an easy starter change for @Ariana-B to make. :)

**Comment by jeremyh** [comment]
> @jeremyh Thanks, this looks great.
> 
> We need to keep in better touch, I'd had this in mind as an easy starter change for @Ariana-B to make. :)

Whoops, sorry - it was too tempting of a friday afternoon fix, though didn't submit it until now. I didn't realise it was now assigned.

**Comment by omad** [comment]
Ruh roh, that didn't fix everything. This is a PR from Jeremy's Fork, and it won't be granted the permissions required. 🤦 

image

**Review by omad — APPROVED** [review]

**Pull request merged**
