### PR TITLE
Add an option to recreate existing dataset extents

### PR DESCRIPTION
**Pull request by jeremyh**
...and do it automatically as part of the schema update, so that the newer, better extents will show up.

Option:
```bash
$ cubedash-gen --recreate-dataset-extents <products...>
```

I've also changed `generate` so that it doesn't spawn any subprocesses at all when workers==1. This makes debugging a little nicer.

### CODE REVIEW

**Review by whatnick — COMMENTED** [review]
Any README.md or docs entries for the fancy all singing all dancing cubedash-gen ?

**Comment by jeremyh** [comment]
I still have 'add readthedocs site' on my list for before the release, for higher-level overview.

But I've expanded a few of the explanations in the `--help` text:
```
$ cubedash-gen --help
Usage: cubedash-gen [OPTIONS] [PRODUCT_NAMES]...

  A tool to generate and update Explorer's caches of datacube data.

  Explorer's view of ODC data is too expensive to calculate on every page
  load (or API call), so Explorer uses its own tables to calculate this
  summary information ahead-of-time.

  The cubedash-gen command creates these summaries in a schema called
  `cubedash`, separate from datacube’s own schema.

  By default, only missing summaries will be added for the specified product
  names; and it will not recreate summaries that already exist.

  ---

  Datacube config

  To choose which datacube to point to, it takes identical datacube config
  (-C) and environment (-E) options as the `datacube` command, and reads
  identical datacube config files and environment variables.

  ie. It will use the datacube that is shown by running the command
  `datacube system check`

  See datacube’s own docs for this configuration handling.

  ---

  Examples

  Create Explorer's schemas and generate all summaries that don't exist:

      cubedash-gen --init --all

  Recreate all summaries for two products:

      cubedash-gen --force-refresh ls8_nbart_scene ls8_level1_scene

  Drop all of Explorer’s additions to the database:

      cubedash-gen --drop

Options:
  -E, --env TEXT
  -C, --config, --config_file TEXT
  --all                           Refresh all products in the datacube, rather
                                  than the specified list.

  -v, --verbose                   Enable all log messages, instead of just
                                  errors.
                                  
                                  Logging goes to stdout unless `--event-log-
                                  file` is specified.
                                  
                                  Logging is coloured plain-text if going to a
                                  tty, and jsonl format otherwise.

  -j, --jobs INTEGER              Number of concurrent worker subprocesses to
                                  use (default: 3)
                                  
                                  This should match how many io-and-cpu-heavy
                                  queries your DB would like to handle
                                  concurrently.

  -l, --event-log-file PATH       Output log messages to file, in jsonl format
  --refresh-stats / --no-refresh-stats
                                  Refresh general statistics tables that cover
                                  all products (default: true)
                                  
                                  This can be slow, and only needs to be done
                                  once (at the end) if calling cubedash-gen
                                  repeatedly

  --force-refresh / --no-force-refresh
                                  Force all time periods to be regenerated,
                                  rather than just the missing ones.
                                  
                                  (default: false)

  --recreate-dataset-extents / --append-dataset-extents
                                  Rebuild Explorer's existing dataset extents
                                  rather than appending new datasets.
                                  (default: false)
                                  
                                  This is useful if you've patched datasets or
                                  products in-place with new geometry or
                                  regions.

  --force-concurrently            Refresh materialised views concurrently in
                                  Postgres. (default: false)
                                  
                                  This will avoid taking any locks when
                                  updating statistics, but has some caveats,
                                  see https://www.postgresql.org/docs/10/sql-
                                  refreshmaterializedview.html

  --init-database, --init / --no-init-database
                                  Create Explorer's schemas, and prepare the
                                  database, before doing anything.

  --drop-database, --drop         Drop all of Explorer's database additions
                                  and exit.

  --help                          Show this message and exit.
```
(the `-E/--env` and `-C/--config` options come from datacube-core, so I can't add help text to them directly here.)

**Comment by jeremyh** [comment]
I should also mention I added the `--drop` command too:  "Drop all of Explorer's database additions and exit." (mirroring the `--init` command)

It's used internally by the tests, and seemed worth exposing publicly on the cli as well.

**Comment by jeremyh** [comment]
Squashed a few commits for cleaner history.

I've added a mention of `cubedash-gen --help` in the readme, hopefully that's good enough for now.

**Review by whatnick — APPROVED** [review]
💯 let's build this and iterate with deployments in staging.

**Pull request merged**
