### PR TITLE
Implement latest stac 1.0.0 beta

### PR DESCRIPTION
**Pull request by jeremyh**
~**Note:** The tests will fail. This works but is still a draft as it's blocked on other PRs to function (see bottom). But I'm raising it now for visibility as it's been sitting in a branch for a while.~ Done!

- Bump stac validation tests from stac 0.9.0 to 1.0.0.beta2 (the latest released beta at time of writing). ( #181)
- Support for eo3 documents in stac conversion (#133)
- Replace most custom stac-item conversion code with eodatasets3 [eo3-to-stac](https://github.com/GeoscienceAustralia/eo-datasets#conversion-to-stac-metadata) library calls (thanks @sachitrajbhandari!)
     - Unifying effort means we can hopefully keep it more updated.
- Allow query params in `/items` pages, as with newer stac-api (#150)
- Include links to the original odc yaml file in the stac links section.
- Includes conversion of legacy `eo` documents to stac items.
- Move all stac URLs consistently under the base of `/stac`, so they follow stac-api conventions. Adds redirects on old URLs to maintain backwards compatibility.
- Support for the `ids` and `collections` parameters when querying stac
- An optional `_full=true` query parameter on Stac searches to return full Stac Item metadata within search results. This can be much slower so is not the default. Can be made the default with [config property](https://github.com/opendatacube/datacube-explorer#how-can-i-configure-the-deployment) `STAC_DEFAULT_FULL_ITEM_INFORMATION = True`

--- 

## Blockages

- [x] `eo3-to-stac` API and improved validation: https://github.com/GeoscienceAustralia/eo-datasets/pull/98

---

## Future ideals
- [ ] the mirroring changes in `stac-to-eo3` _odc-tools_ (not a direct dependency of this PR): https://github.com/opendatacube/odc-tools/pull/96

### CODE REVIEW

**Comment by jeremyh** [comment]
The build works locally, but is hitting an error in pytest collection within Github Actions. @omad mentioned similar problems have been  happening elsewhere too.

```

==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:994: in _gcd_import
    ???
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:955: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:665: in _load_unlocked
    ???
/env/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:171: in exec_module
    exec(co, module.__dict__)
integration_tests/conftest.py:15: in <module>
    import cubedash
cubedash/__init__.py:6: in <module>
    from ._pages import app
cubedash/_pages.py:13: in <module>
    from cubedash import _audit, _monitoring
cubedash/_audit.py:14: in <module>
    from . import _model
cubedash/_model.py:17: in <module>
    from cubedash.summary import SummaryStore, TimePeriodOverview
cubedash/summary/__init__.py:3: in <module>
    from ._stores import SummaryStore
cubedash/summary/_stores.py:31: in <module>
    from sqlalchemy.engine import Engine, RowProxy
E   ImportError: cannot import name 'RowProxy'
```

**Comment by whatnick** [comment]
@jeremyh I am using this PR to try and fix the CI : https://github.com/opendatacube/datacube-explorer/pull/210 expect something later today.

**Comment by whatnick** [comment]
@jez are there DB schema chages required for this PR ?

**Comment by jeremyh** [comment]
> @jez are there DB schema chages required for this PR ?

Nope! 🙂

**Review by alexgleith — APPROVED** [review]

**Pull request merged**
