### PR TITLE
Makefile help and switch versioning library

### PR DESCRIPTION
**Pull request by omad**
**1.** Add usage instructions to the `Makefile`:
image

**2.**
Switch to using the modern `setuptools_scm` instead of the ancient and problematic `versioneer`.

### CODE REVIEW

**Review by alexgleith — DISMISSED** [review]
Very nice!

**Review by jeremyh — DISMISSED** [review]
:+1:

**Review by alexgleith — APPROVED** [review]
I just did this, but you beat me to it!

**Comment by omad** [comment]
Sorry! We should work on ownership a bit more :)

**Pull request merged**
