### PR TITLE
Add tests for legacy-db support & a page-test cli-tool

### PR DESCRIPTION
**Pull request by jeremyh**
These reproduce #169 on my system.

... and they're fixed [accidentally] by the code clean-up in #167 

This also adds functions that will allow us to experiment more with tests of Explorer in unusual
Index situations. You can modify the Index, and then "load all pages to see if any fall over".

There's also a second commit which fixes another edge-case it found.

### CODE REVIEW

**Comment by jeremyh** [comment]
Extracted the test-all-pages function into a cli tool called `cubedash-page-test`: https://asciinema.org/a/7WRNe4efZFUyfchWRBUXwb3hJ

This is useful for running against local copies of "real" datacubes, like Africa and NCI, which are more useful tests than our test data alone. In theory, you could run it against a remote Explorer too...

**Comment by jeremyh** [comment]
Converting back to a draft -- that's a _big_ increase in test run time. (it isn't as big locally). 

I might need to combine some of the test data loads.

**Comment by jeremyh** [comment]
A new release of Black came out, and we're unfortunately not pinning the version of Black in our Docker container so it's broken the lint build. Added a commit to move to the new version.

**Comment by jeremyh** [comment]
The tests are now (slightly) faster than without this PR, despite adding meaningful (non-%) coverage. Marked as ready for review. :tada:

**Review by alexgleith — APPROVED** [review]

**Pull request merged**
